version: '3.9'

services:
  backend:
    image: ghcr.io/yosefxk/tzeva-adom-backend:latest
    container_name: tzeva-adom-backend
    restart: unless-stopped
    volumes:
      - alert_radar_data:/app/database
    networks:
      - media_network

  frontend:
    image: ghcr.io/yosefxk/tzeva-adom-frontend:latest
    container_name: tzeva-adom-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - media_network

volumes:
  alert_radar_data:
    driver: local

networks:
  media_network:
    external: true
